server:
  port: 8443 # 端口
  compression:
    enabled: true
  http2:
    enabled: true # 启用http2
  ssl:
    enabled: true
    key-store: classpath:keystore.p12 # 启用http2
    key-store-password: 123456 # 证书密码
    key-store-type: PKCS12 # 证书类型
    protocol: TLSv1.2 # 协议类型
    key-alias: undertow